"""Preview plots and text summaries for prepared C2S datasets."""

from collections import Counter
from pathlib import Path

import anndata
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

from src.data.dataset_config import DatasetConfig


SPLIT_ORDER = ("train", "val", "test")
SPLIT_LABELS = {
    "train": "Train",
    "val": "Validation",
    "test": "Test",
}
SPLIT_COLORS = {
    "train": "#4c78a8",
    "val": "#f58518",
    "test": "#54a24b",
}

_MANAGED_PREVIEW_PATTERNS = (
    "*_distribution.png",
    "*_distribution_raw.png",
    "*_distribution_filtered.png",
    "dataset_summary.txt",
    "num_genes_histogram.png",
    "qc_violin.png",
    "umap_*.png",
)


def clear_managed_preview_outputs(preview_dir: Path) -> None:
    """Remove stale files generated by this preview module."""

    for pattern in _MANAGED_PREVIEW_PATTERNS:
        for path in preview_dir.glob(pattern):
            if path.is_file():
                path.unlink()


def save_qc_violin(adata: anndata.AnnData, preview_dir: Path) -> None:
    fig, axes = plt.subplots(1, 3, figsize=(12, 4))
    for ax, col in zip(axes, ["n_genes_by_counts", "total_counts", "pct_counts_mt"]):
        ax.violinplot(adata.obs[col], positions=[0], showmedians=True)
        ax.set_title(col)
        ax.set_xticks([])
        ax.grid(axis="y", color="#d9dce3", alpha=0.6)
    fig.suptitle("QC metrics (after filtering)")
    fig.tight_layout()
    fig.savefig(preview_dir / "qc_violin.png", dpi=150)
    plt.close(fig)
    print("  Saved qc_violin.png")


def _split_dataset_column(
    split_datasets: dict,
    split_name: str,
    col: str,
    *,
    required: bool = False,
) -> list:
    dataset = split_datasets[split_name]
    if col not in getattr(dataset, "column_names", []):
        if required:
            raise ValueError(f"Split '{split_name}' is missing required column '{col}'.")
        return []
    return list(dataset[col])


def _split_counters(
    split_datasets: dict,
    col: str,
    *,
    required: bool = False,
) -> dict[str, Counter]:
    return {
        split_name: Counter(
            str(value)
            for value in _split_dataset_column(
                split_datasets,
                split_name,
                col,
                required=required,
            )
        )
        for split_name in SPLIT_ORDER
    }


def _ordered_categories(counters: dict[str, Counter], max_categories: int = 30) -> list[str]:
    totals = Counter()
    for counter in counters.values():
        totals.update(counter)
    return [category for category, _ in totals.most_common(max_categories)]


def _split_assignments(split_datasets: dict) -> dict[str, str]:
    assignments: dict[str, str] = {}
    for split_name in SPLIT_ORDER:
        for cell_name in _split_dataset_column(
            split_datasets,
            split_name,
            "cell_name",
            required=True,
        ):
            assignments[str(cell_name)] = split_name
    return assignments


def run_umap(
    adata: anndata.AnnData,
    ds_cfg: DatasetConfig,
    preview_dir: Path,
    seed: int,
    split_datasets: dict,
) -> None:
    import pandas as pd
    import scanpy as sc

    split_by_cell = _split_assignments(split_datasets)
    obs_names = [str(name) for name in adata.obs_names]
    keep_mask = [name in split_by_cell for name in obs_names]
    if not any(keep_mask):
        raise ValueError(
            "Cannot annotate UMAP by split because no Arrow cell_name values "
            "match AnnData obs_names."
        )

    adata_umap = adata[keep_mask, :].copy()
    split_values = [split_by_cell[str(name)] for name in adata_umap.obs_names]
    adata_umap.obs["split"] = pd.Categorical(
        split_values,
        categories=list(SPLIT_ORDER),
        ordered=True,
    )

    print("Computing PCA + UMAP ...")
    sc.tl.pca(adata_umap, random_state=seed)
    sc.pp.neighbors(adata_umap)
    sc.tl.umap(adata_umap, random_state=seed)

    split_fname = "umap_cell_types_by_split.png"
    _save_umap_by_split(
        adata_umap,
        color_col=ds_cfg.cell_type_col,
        title=f"{ds_cfg.name} - cell types by split",
        out_path=preview_dir / split_fname,
    )
    print(f"  Saved {split_fname}")


def _save_umap_by_split(
    adata: anndata.AnnData,
    color_col: str,
    title: str,
    out_path: Path,
) -> None:
    coords = adata.obsm["X_umap"]
    color_values = adata.obs[color_col].astype(str).to_numpy()
    split_values = adata.obs["split"].astype(str).to_numpy()
    categories = sorted(set(color_values))
    cmap = plt.get_cmap("tab20", max(len(categories), 1))
    category_colors = {
        category: cmap(i % cmap.N)
        for i, category in enumerate(categories)
    }
    point_size = max(2.0, min(10.0, 50_000 / max(adata.n_obs, 1)))

    fig, axes = plt.subplots(
        1,
        len(SPLIT_ORDER),
        figsize=(5.2 * len(SPLIT_ORDER), 5.0),
        sharex=True,
        sharey=True,
    )
    if len(SPLIT_ORDER) == 1:
        axes = [axes]

    for ax, split_name in zip(axes, SPLIT_ORDER):
        split_mask = split_values == split_name
        for category in categories:
            mask = split_mask & (color_values == category)
            if not mask.any():
                continue
            ax.scatter(
                coords[mask, 0],
                coords[mask, 1],
                s=point_size,
                c=[category_colors[category]],
                alpha=0.8,
                linewidths=0,
                label=category,
            )
        ax.set_title(f"{SPLIT_LABELS[split_name]} (n={int(split_mask.sum()):,})")
        ax.set_xlabel("UMAP1")
        ax.set_ylabel("UMAP2")
        ax.set_xticks([])
        ax.set_yticks([])
        ax.set_frame_on(False)

    handles = [
        plt.Line2D(
            [0],
            [0],
            marker="o",
            linestyle="",
            color=category_colors[category],
            label=category,
            markersize=6,
        )
        for category in categories
    ]
    fig.legend(
        handles=handles,
        loc="center left",
        bbox_to_anchor=(1.0, 0.5),
        fontsize=8 if len(categories) > 8 else 9,
    )
    fig.suptitle(title)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def _split_horizontal_bar(
    counters: dict[str, Counter],
    title: str,
    xlabel: str,
    out_path: Path,
    max_bars: int = 30,
) -> None:
    categories = _ordered_categories(counters, max_categories=max_bars)
    if not categories:
        print(f"  Skipped {out_path.name} (no values)")
        return

    y = np.arange(len(categories))
    bar_height = 0.22
    offsets = {
        "train": -bar_height,
        "val": 0.0,
        "test": bar_height,
    }
    max_count = max(
        max((counter.get(category, 0) for category in categories), default=0)
        for counter in counters.values()
    )

    fig, ax = plt.subplots(figsize=(9, max(3.5, len(categories) * 0.55)))
    for split_name in SPLIT_ORDER:
        counts = np.array([counters[split_name].get(category, 0) for category in categories])
        bars = ax.barh(
            y + offsets[split_name],
            counts,
            height=bar_height,
            color=SPLIT_COLORS[split_name],
            alpha=0.9,
            label=SPLIT_LABELS[split_name],
        )
        for bar, count in zip(bars, counts):
            if count == 0:
                continue
            ax.text(
                bar.get_width() + max(max_count * 0.01, 0.5),
                bar.get_y() + bar.get_height() / 2,
                f"{int(count):,}",
                va="center",
                fontsize=7,
            )

    ax.set_yticks(y)
    ax.set_yticklabels(categories, fontsize=8)
    ax.invert_yaxis()
    ax.set_xlabel(xlabel)
    ax.set_title(title)
    ax.grid(axis="x", color="#d9dce3", alpha=0.6)
    ax.legend(loc="lower right")
    ax.set_xlim(right=max_count * 1.18 if max_count else 1)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def save_distribution_plots(
    split_datasets: dict,
    ds_cfg: DatasetConfig,
    preview_dir: Path,
) -> None:
    for col, fname_prefix, title_label in ds_cfg.distribution_plot_specs:
        if not any(col in getattr(split_datasets[name], "column_names", []) for name in SPLIT_ORDER):
            continue
        _split_horizontal_bar(
            _split_counters(split_datasets, col),
            title=f"{title_label} distribution by split",
            xlabel="Cell count",
            out_path=preview_dir / f"{fname_prefix}_distribution.png",
        )
        print(f"  Saved {fname_prefix}_distribution.png")


def save_num_genes_histogram(split_datasets: dict, preview_dir: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4))
    for split_name in SPLIT_ORDER:
        values = _split_dataset_column(split_datasets, split_name, "num_genes")
        if not values:
            continue
        num_genes_arr = np.array(values)
        ax.hist(
            num_genes_arr,
            bins=60,
            color=SPLIT_COLORS[split_name],
            alpha=0.45,
            edgecolor="white",
            label=(
                f"{SPLIT_LABELS[split_name]} "
                f"(n={len(num_genes_arr):,}, median={int(np.median(num_genes_arr))})"
            ),
        )

    ax.set_xlabel("Genes per cell sentence")
    ax.set_ylabel("Cells")
    ax.set_title("num_genes distribution by split")
    ax.legend()
    ax.grid(axis="y", color="#d9dce3", alpha=0.6)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    fig.tight_layout()
    fig.savefig(preview_dir / "num_genes_histogram.png", dpi=150)
    plt.close(fig)
    print("  Saved num_genes_histogram.png")


def _format_num_genes_stats(values: list) -> str:
    if not values:
        return "n/a"
    arr = np.array(values)
    return (
        f"min={int(arr.min()):,}, "
        f"median={int(np.median(arr)):,}, "
        f"max={int(arr.max()):,}"
    )


def save_text_summary(
    adata_raw: anndata.AnnData,
    adata_filtered: anndata.AnnData,
    arrow_ds,
    split_datasets: dict,
    vocab: list[str],
    ds_cfg: DatasetConfig,
    preview_dir: Path,
) -> None:
    num_genes_arr = np.array(arrow_ds["num_genes"])
    ct_col = ds_cfg.cell_type_col
    split_sizes = {
        split_name: len(split_datasets[split_name])
        for split_name in SPLIT_ORDER
    }
    split_total = sum(split_sizes.values())

    lines = [
        "=" * 70,
        f"Dataset: {ds_cfg.name}",
        "=" * 70,
        "",
        "-- Filtering ----------------------------------------------------",
        f"  Raw    : {adata_raw.shape[0]:>7,} cells x {adata_raw.shape[1]:>6,} genes",
        f"  Final  : {adata_filtered.shape[0]:>7,} cells x {adata_filtered.shape[1]:>6,} genes",
        "",
        "-- Normalization ------------------------------------------------",
        "  sc.pp.normalize_total  ->  sc.pp.log1p(base=10)",
        "",
        "-- C2S Dataset --------------------------------------------------",
        f"  Total cells before split filtering : {len(arrow_ds):,}",
        f"  Saved split cells                  : {split_total:,}",
        f"  Held-out cells removed by vocab    : {len(arrow_ds) - split_total:,}",
        f"  Train vocabulary                   : {len(vocab):,} unique genes",
        f"  Overall num_genes                  : {_format_num_genes_stats(num_genes_arr.tolist())}",
        "",
        "-- Split sizes ---------------------------------------------------",
    ]
    for split_name in SPLIT_ORDER:
        pct = 100 * split_sizes[split_name] / max(split_total, 1)
        num_stats = _format_num_genes_stats(_split_dataset_column(split_datasets, split_name, "num_genes"))
        lines.append(
            f"  {SPLIT_LABELS[split_name]:<10} "
            f"{split_sizes[split_name]:>7,} cells  "
            f"({pct:>5.1f}%)  num_genes {num_stats}"
        )

    counters = _split_counters(split_datasets, ct_col, required=True)
    categories = _ordered_categories(counters, max_categories=1000)
    lines.extend([
        "",
        "-- Cell-type breakdown by split -------------------------------",
        "  cell_type                         train     val    test   total",
    ])
    for category in categories:
        counts = [counters[split_name].get(category, 0) for split_name in SPLIT_ORDER]
        total = sum(counts)
        lines.append(
            f"  {category:<30} "
            f"{counts[0]:>7,} {counts[1]:>7,} {counts[2]:>7,} {total:>7,}"
        )

    lines.append("=" * 70)

    summary_path = preview_dir / "dataset_summary.txt"
    summary_path.write_text("\n".join(lines))
    print("  Saved dataset_summary.txt")
